spring:
  application:
    name: backend-spring
  rabbitmq:
    username: user
    password: password
    host: localhost
    port: 5672
    queue:
      output_queue: todo_queue
      input_queue: done_queue
config:
  minio:
    url: http://localhost:9000
    user: admin
    password: password123

    buckets:
      text: text-bucket
      speech: speech-bucket

  jwt:
    expiration-days: 7
    secret: 675f1e19f9bc429dde298da7c88a676c # todo: Replace with environment variable ;) <==3