spring:
  application:
    name: backend-spring
  datasource:
    url: jdbc:postgresql://localhost:5432/tts_db
    username: root
    password: rootpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

config:
  minio:
    url: http://localhost:9000
    user: admin
    password: password123

  buckets:
    name: yourBucketName